name: "Pull Request Labeler"

on:
  workflow_dispatch:
#  pull_request_target:
 #   types: [opened, synchronize]

permissions:
  contents: read

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: srvaroa/labeler@e216fb40e2e6d3b17d90fb1d950f98bee92f65ce # master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout code at the provided SHA
        uses: actions/checkout@v4
        with:
          # Checkout the exact SHA passed via environment variable
          ref: ${{ env.COMMON_IDENTIFIER }}

      - name: Create Completion Flag
        run:  echo "Labeler workflow completed for SHA: ${{ env.COMMON_IDENTIFIER }}" > LABELER_flag_${{ env.COMMON_IDENTIFIER }}.txt


      - name: Upload completion artifact
        uses: actions/upload-artifact@v4
        with:
          name: workflow-LABELER-completed_${{ env.COMMON_IDENTIFIER }}
          path: LABELER_flag_${{ env.COMMON_IDENTIFIER }}.txt
