name: Parent Workflow

on: [pull_request]

permissions:
  contents: write
  pages: write
  pull-requests: write
  id-token: write
#test11
jobs:
  trigger-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger "Check Amalgamation" Workflow
        run: gh workflow run "Check amalgamation"
        env:
          GH_TOKEN: ${{ secrets.PARENT_WORKFLOW_TRIGGER }}

      - name: Trigger "Test Trudag Extensions" Workflow
        run: gh workflow run "Test Trudag extensions"
        env:
          GH_TOKEN: ${{ secrets.PARENT_WORKFLOW_TRIGGER }}

      - name: Trigger "Pull Request Labeler" Workflow
        run: gh workflow run "Pull Request Labeler"
        env:
          GH_TOKEN: ${{ secrets.PARENT_WORKFLOW_TRIGGER }}

      - name: Wait and Download Artifacts From Child Workflows
        env:
          GH_TOKEN: ${{ secrets.PARENT_WORKFLOW_TRIGGER }}
        run: |
          echo "Waiting for artifacts from child workflows..."

          # List of required artifacts
          REQUIRED_ARTIFACTS=(
            workflow-AMALGAMATION-completed
            workflow-TRUDAG-EXTENSIONS-completed
            workflow-LABELER-completed
          )

          COMPLETED=false
          MAX_RETRIES=60  # Retry up to 60 times (15 mins with 15s intervals)
          RETRY_COUNT=0

          while [ "$COMPLETED" = "false" ] && [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            COMPLETED=true # Assume all artifacts exist initially

            for ARTIFACT in "${REQUIRED_ARTIFACTS[@]}"; do
              echo "Attempting to download artifact: $ARTIFACT"

              # Create a unique folder for this artifact to avoid overwriting
              ARTIFACT_DIR="artifacts/$ARTIFACT"
              mkdir -p "$ARTIFACT_DIR"

              # Download the artifact to the unique folder
              gh run download --name "$ARTIFACT" --dir "$ARTIFACT_DIR" || COMPLETED=false
            done

            if [ "$COMPLETED" = "false" ]; then
              echo "Not all artifacts are ready. Waiting 15 seconds..."
              sleep 15
              RETRY_COUNT=$((RETRY_COUNT + 1))
            fi
          done

          if [ "$COMPLETED" = "false" ]; then
            echo "Timed out while waiting for artifacts."
            exit 1
          fi

          echo "All required artifacts have been downloaded successfully!"

      - name: Verify Artifacts
        run: |
          echo "Listing downloaded files..."
          ls -Rl artifacts/
