name: Parent Workflow

on: [pull_request]

permissions:
  contents:  write
  pages: write
  pull-requests: write
  id-token: write

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger "Check Amalgamation" Workflow
        run: gh workflow run "Check amalgamation"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Trigger "Dependency Review" Workflow
        run: gh workflow run "Dependency Review"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Trigger "Test Trudag Extensions" Workflow
        run: gh workflow run "Test Trudag extensions"
        env:
          GH_TOKEN: ${{ github.token }}

      #- name: Trigger "CIFuzz" Workflow
      #  run: gh workflow run "CIFuzz"

      - name: Trigger "Pull Request Labeler" Workflow
        run: gh workflow run "Pull Request Labeler"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Trigger "Ubuntu" Workflow
        run: gh workflow run "Ubuntu"
        env:
          GH_TOKEN: ${{ github.token }}