name: Parent Workflow

on: [pull_request]

permissions:
  contents:  write
  pages: write
  pull-requests: write
  id-token: write

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger "Check Amalgamation" Workflow
        run: gh workflow run "Check amalgamation"
        env:
          GH_TOKEN: ${{ secrets.PARENT_WORKFLOW_TRIGGER }}

      - name: Trigger "Test Trudag Extensions" Workflow
        run: gh workflow run "Test Trudag extensions"
        env:
          GH_TOKEN: ${{ secrets.PARENT_WORKFLOW_TRIGGER }}

      #- name: Trigger "CIFuzz" Workflow
      #  run: gh workflow run "CIFuzz"

      - name: Trigger "Pull Request Labeler" Workflow
        run: gh workflow run "Pull Request Labeler"
        env:
          GH_TOKEN: ${{ secrets.PARENT_WORKFLOW_TRIGGER }}


      - name: Wait for All Artifacts
        run: |
          REQUIRED_ARTIFACTS=(
            artifact-workflow-AMALGAMATION-completed
            artifact-workflow-TRUDAG-EXTENSIONS-completed
            artifact-workflow-PULL-REQUEST-LABELER-completed
          )

          COMPLETED=false
          while [ "$COMPLETED" = "false" ]; do
            COMPLETED=true # Assume all artifacts are found

            for ARTIFACT in "${REQUIRED_ARTIFACTS[@]}"; do
              if [[ ! -f "$ARTIFACT" ]]; then
                COMPLETED=false
                echo "Waiting for $ARTIFACT..."
              fi
            done

            if [ "$COMPLETED" = "false" ]; then
              echo "Not all artifacts are ready. Sleeping for 30 seconds..."
              sleep 30
            fi
          done

          echo "All required artifacts are now available."