name: Test Trudag extensions

on:
  workflow_dispatch:
  #push:
   # branches: [ main ]
  #pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.2'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install trustable --index-url https://gitlab.com/api/v4/projects/66600816/packages/pypi/simple
    
    - name: Run tests
      run: |
        cd .dotstop_extensions
        pytest -v

    - name: Checkout code at the provided SHA
      uses: actions/checkout@v4
      with:
          # Checkout the exact SHA passed via environment variable
          ref: ${{ env.COMMON_IDENTIFIER }}

    - name: Create Completion Flag
      run: echo "Trudag extensions workflow completed." > TRUDAG_EXTENSIONS_flag_${{ env.COMMON_IDENTIFIER }}.txt

    - name: Upload completion artifact
      uses: actions/upload-artifact@v4
      with:
        name: workflow-TRUDAG-EXTENSIONS-completed_${{ env.COMMON_IDENTIFIER }}
        path: TRUDAG_EXTENSIONS_flag_${{ env.COMMON_IDENTIFIER }}.txt