name: Test Trudag extensions

on:
  workflow_dispatch:
  #push:
   # branches: [ main ]
  #pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.2'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install trustable --index-url https://gitlab.com/api/v4/projects/66600816/packages/pypi/simple
    
    - name: Run tests
      run: |
        cd .dotstop_extensions
        pytest -v

    - name: Upload Trudag test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trudag-test-data
        path: docs/s-core/trustable/generated/
        if-no-files-found: warn

    - name: Upload completion artifact
      uses: actions/upload-artifact@v4
      with:
        name: workflow-TRUDAG_EXTENSIONS-completed
        path: completion_flag.txt